# Generated by Django 5.2.13 on 2026-05-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_add_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek (Lotin)')], default='en', help_text='Detected (or user-overridden) language of the paper text. Summaries and chat replies are generated in this language.', max_length=5),
        ),
        migrations.AddField(
            model_name='paper',
            name='language_confidence',
            field=models.FloatField(default=0.0, help_text='Detector confidence 0.0–1.0. 0.0 means user-provided or unknown.'),
        ),
    ]
