"""
Adds Russian and Uzbek translations for the dashboard strings (and compiles
to .mo) without needing GNU gettext tools in the container.

Idempotent: if an entry already exists with a non-empty msgstr, leave it alone.
If it exists but is empty, fill it. If it doesn't exist, append it.
"""
from __future__ import annotations

import sys
from pathlib import Path

import polib

REPO = Path(__file__).resolve().parent.parent
LOCALE = REPO / 'locale'

# ── Singular strings ────────────────────────────────────────────────────
SINGULAR = {
    "Dashboard — Academic Summarizer": {
        "ru": "Панель — Academic Summarizer",
        "uz": "Boshqaruv paneli — Academic Summarizer",
    },
    "Your reading room": {
        "ru": "Ваш читальный зал",
        "uz": "Sizning o'qish xonangiz",
    },
    "Nothing here yet": {
        "ru": "Здесь пока пусто",
        "uz": "Bu yerda hali hech narsa yo'q",
    },
    "Your dashboard fills up once you upload a paper.": {
        "ru": "Панель заполнится, как только вы загрузите первый документ.",
        "uz": "Panel siz birinchi maqolani yuklaganingizda to'ldiriladi.",
    },
    "Stats, charts, and a tag cloud appear here as you summarize. Start with one paper — it takes about twenty seconds.": {
        "ru": "Статистика, графики и облако тегов появятся здесь по мере работы. Начните с одной статьи — это занимает около двадцати секунд.",
        "uz": "Statistika, diagrammalar va teglar buluti siz xulosalashtirgan sayin shu yerda paydo bo'ladi. Bitta maqola bilan boshlang — bu taxminan yigirma soniya oladi.",
    },
    "uploaded to your library": {
        "ru": "загружено в библиотеку",
        "uz": "kutubxonangizga yuklangan",
    },
    "Summaries": {
        "ru": "Резюме",
        "uz": "Xulosalar",
    },
    "generated by Llama 3.3": {
        "ru": "создано Llama 3.3",
        "uz": "Llama 3.3 tomonidan yaratilgan",
    },
    "distinct topics covered": {
        "ru": "уникальных тем охвачено",
        "uz": "noyob mavzu qamrab olingan",
    },
    "Time saved": {
        "ru": "Время сэкономлено",
        "uz": "Vaqt tejaldi",
    },
    "vs. reading every paper": {
        "ru": "против чтения каждой статьи",
        "uz": "har bir maqolani o'qishga nisbatan",
    },
    "Languages": {
        "ru": "Языки",
        "uz": "Tillar",
    },
    "in your library": {
        "ru": "в вашей библиотеке",
        "uz": "kutubxonangizda",
    },
    "Active days": {
        "ru": "Активные дни",
        "uz": "Faol kunlar",
    },
    "with uploads or chat": {
        "ru": "с загрузками или чатом",
        "uz": "yuklash yoki chat bilan",
    },
    "Activity": {
        "ru": "Активность",
        "uz": "Faollik",
    },
    "Papers per day · last 30 days": {
        "ru": "Статей в день · за последние 30 дней",
        "uz": "Kuniga maqolalar · oxirgi 30 kun",
    },
    "Distribution": {
        "ru": "Распределение",
        "uz": "Taqsimot",
    },
    "By language": {
        "ru": "По языку",
        "uz": "Til bo'yicha",
    },
    "Top tags": {
        "ru": "Топ теги",
        "uz": "Eng yaxshi teglar",
    },
    "Most-used in your library": {
        "ru": "Самые используемые в вашей библиотеке",
        "uz": "Kutubxonangizda eng ko'p ishlatilganlar",
    },
    "Tag cloud": {
        "ru": "Облако тегов",
        "uz": "Teglar buluti",
    },
    "Every tag, sized by use": {
        "ru": "Все теги, размер по частоте использования",
        "uz": "Barcha teglar, hajmi foydalanish chastotasiga ko'ra",
    },
    "Recent activity": {
        "ru": "Недавняя активность",
        "uz": "So'nggi faollik",
    },
    "What you've been reading": {
        "ru": "Что вы читали",
        "uz": "Nimani o'qiyotgan edingiz",
    },
    "all papers": {
        "ru": "все статьи",
        "uz": "barcha maqolalar",
    },
    "New paper": {
        "ru": "Новая статья",
        "uz": "Yangi maqola",
    },
    "Welcome back, %(name)s.": {
        "ru": "С возвращением, %(name)s.",
        "uz": "Qaytib kelganingizdan xursandmiz, %(name)s.",
    },
}

# ── Plural strings ──────────────────────────────────────────────────────
# Key = singular msgid. Each language maps to the ordered list of plural
# forms required by that language's Plural-Forms header.
#   ru: 3 forms (one / few / many)
#   uz: 2 forms (one / other)  ← langdef but with our nplurals=2 header
PLURAL = {
    ("%(counter)s tag", "%(counter)s tags"): {
        "ru": ["%(counter)s тег", "%(counter)s тега", "%(counter)s тегов"],
        "uz": ["%(counter)s teg", "%(counter)s teg"],
    },
    ("%(counter)s paper", "%(counter)s papers"): {
        "ru": ["%(counter)s статья", "%(counter)s статьи", "%(counter)s статей"],
        "uz": ["%(counter)s maqola", "%(counter)s maqola"],
    },
}


def upsert(po: polib.POFile, msgid: str, msgstr: str) -> str:
    """Returns 'added' | 'filled' | 'kept'."""
    entry = po.find(msgid)
    if entry is None:
        entry = polib.POEntry(msgid=msgid, msgstr=msgstr)
        po.append(entry)
        return 'added'
    if entry.msgstr.strip():
        return 'kept'
    entry.msgstr = msgstr
    return 'filled'


def upsert_plural(po: polib.POFile, msgid: str, msgid_plural: str,
                  forms: list[str]) -> str:
    entry = po.find(msgid)
    if entry is None:
        entry = polib.POEntry(
            msgid=msgid,
            msgid_plural=msgid_plural,
            msgstr_plural={i: forms[i] for i in range(len(forms))},
        )
        po.append(entry)
        return 'added'
    has_any = any(v.strip() for v in entry.msgstr_plural.values())
    if has_any:
        return 'kept'
    entry.msgid_plural = msgid_plural
    entry.msgstr_plural = {i: forms[i] for i in range(len(forms))}
    return 'filled'


def main() -> int:
    overall = {}
    for lang in ('ru', 'uz'):
        po_path = LOCALE / lang / 'LC_MESSAGES' / 'django.po'
        mo_path = po_path.with_suffix('.mo')
        if not po_path.exists():
            print(f'!! {po_path} missing; skipping')
            continue
        po = polib.pofile(str(po_path))

        counts = {'added': 0, 'filled': 0, 'kept': 0}
        for msgid, by_lang in SINGULAR.items():
            counts[upsert(po, msgid, by_lang[lang])] += 1
        for (msgid, msgid_plural), by_lang in PLURAL.items():
            counts[upsert_plural(po, msgid, msgid_plural, by_lang[lang])] += 1

        po.save(str(po_path))
        po.save_as_mofile(str(mo_path))
        overall[lang] = counts
        print(f'{lang}: {counts}  → wrote {po_path.name} + {mo_path.name}')

    return 0 if overall else 1


if __name__ == '__main__':
    sys.exit(main())
